version: 2.1
orbs:
  node: circleci/node@4.3.0
  slack: circleci/slack@4.4.2
machine:
  pre:
    - mkdir ~/.yarn-cache
dependencies:
  cache_directories:
    - ~/.yarn-cache
jobs:
  test_all:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - node/install-yarn:
          version: 1.22.0
      - run: |
          yarn install
          yarn run compile
#          yarn run test
#      - slack/notify:
#          channel: build
#          event: fail
#          template: basic_fail_1
workflows:
  test:
    jobs:
      - test_all:
          context: slack-secret
